name: Automated Windows Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup MSBuild Configuration
      uses: microsoft/setup-msbuild@v2

    # Собираем напрямую файл проекта Tervylla.vcxproj в режиме Release под x64
    - name: Compile C++ Project
      run: msbuild Tervylla.vcxproj /p:Configuration=Release /p:Platform=x64

    # Забираем скомпилированный готовый файл .exe или .dll
    - name: Save Compiled Files
      uses: actions/upload-artifact@v4
      with:
        name: Finished-Program
        path: |
          **/Release/**/*.exe
          **/Release/**/*.dll
          **/x64/Release/**/*.exe
          **/x64/Release/**/*.dll
